# docker-compose.yaml
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    restart: on-failure
    ports:
      - 8081:8081
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_OPTS="--httpPort=8081"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: